import Head from 'next/head'
import Image from 'next/image'
import styles from '../styles/Home.module.css'
import Header from '../components/Header'
import Hero from '../components/Hero'
import AboutMe from '../components/about/AboutMe'
import Services from '../components/Services'
import Contact from '../components/contact/Contact'
import AOS from 'aos';
import 'aos/dist/aos.css';
import { useEffect,useState, useRef } from 'react';
import Scroller from '../components/scroller'
export default function Home() {
  useEffect(() => {
    AOS.init();
  }, []);
  return (
    <div className={styles.container}>
      <Scroller/>
      <Head>
        <title>Media Floats</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="../image/icon.png" />
        <link rel="preconnect" href="https://fonts.googleapis.com"/>
        <link rel="preconnect" href="https://fonts.googleapis.com"></link>
        <link href='https://fonts.googleapis.com/css?family=Noto Serif' rel='stylesheet'></link>
      
      </Head>
      <Header/>
      <Hero/>
      <AboutMe/>
      <Services/>
      <Contact/>
    </div>
  )
}
